### PR TITLE
Added some cljs-time functions

### PR DESCRIPTION
**Pull request by dom8509**
* added date-time, year, month and day to cljs-time.core
* added from-long to cljs-time.coerce

### CODE REVIEW

**Comment by logseq-cldwalker** [comment]
Hi. Thanks for contributing. As mentioned in [the readme](https://github.com/logseq/nbb-logseq#contributing), we'd prefer discussion first for contributions. What are you looking to do by extending time namespaces?

**Comment by dom8509** [comment]
Hello and sorry, next time I will add a discussion first:) 
I created a script based on nbb-logseq to export my logseq graph to markdown. To create my markdown metadata, I needed the methods I added to the namespace.  
See: https://github.com/dom8509/logseq-to-markdown/blob/main/src/logseq_to_markdown/utils.cljs
I also tried to add them to deps.edn for my own cljs-time version, but nbb-logseq always used the methods of the cljs-time package inside nbb-logseq.

I have already created my own version of nbb-logseq that I use in my code, but I thought it might be useful to you as well. 
If I am using the cljs-time component of nbb-logseq incorrectly and there is another way to extend and use the time functions without adding them to the nbb-logseq namespace, please let me know.

**Comment by logseq-cldwalker** [comment]
No worries. Cool to see you're using nbb-logseq for publishing efforts

> I have already created my own version of nbb-logseq that I use in my code, but I thought it might be useful to you as well.
If I am using the cljs-time component of nbb-logseq incorrectly and there is another way to extend and use the time functions without adding them to the nbb-logseq namespace, please let me know.

Unfortunately for libraries that come bundled with nbb-logseq (which are few), adding them through sci is the only way. This PR is reasonably small and we'd love to encourage publishing efforts in nbb-logseq

**Comment by logseq-cldwalker** [comment]
0.7.135 has been released with these changes

**Pull request merged**
